services:
  - type: web
    name: xstro-md
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_ID
        sync: false
      - key: SUDO
        sync: false
      - key: CMD_REACT
        sync: false
      - key: BOT_INFO
        sync: false
      - key: PORT
        value: "8000"
