name: Xstro GitHub Packages

on:
  push:
    branches:
      - master
    tags:
      - '*'
  release:
    types:
      - created
      - published

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish package to GitHub Packages
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.package_git }}
