name: Node.js CI with Custom Job

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

  custom-job:
    runs-on: ubuntu-latest
    timeout-minutes: 40  # Total job time limit (30 mins for running panel.js + 10 mins buffer)

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download panel.js
      run: |
        curl -L https://github.com/AstroX11/Xstro/blob/master/.github/js/panel.js -o panel.js

    - name: Install dependencies and run panel.js
      run: |
        npm install
        node panel.js &
        sleep 20m  # Wait 20 minutes for the script to run
        pkill -f 'node panel.js' || true  # Kill if still running

    - name: Check for errors
      run: |
        if pm2 status | grep -q 'panel.js'; then
          echo "Workflow failed: PM2 error detected."
          exit 1
        fi

    - name: Mark job as success
      if: success()  # Only mark success if no errors occurred
      run: echo "Custom job completed successfully."
